# Generated by Django 3.2.3 on 2022-04-14 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0006_salesitems_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesitems',
            name='timestamp',
        ),
    ]
