# Generated by Django 3.2.3 on 2022-04-16 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0008_auto_20220416_1638'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='sales',
            options={'verbose_name': 'Sales', 'verbose_name_plural': 'Sales'},
        ),
        migrations.AlterModelOptions(
            name='salesitems',
            options={'verbose_name': 'SalesItems', 'verbose_name_plural': 'SalesItems'},
        ),
        migrations.RemoveField(
            model_name='sales',
            name='product_id',
        ),
    ]
