# Generated by Django 3.2.3 on 2022-04-17 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0009_auto_20220416_1652'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
